import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/src/contexts/AuthContext";

const MontSerrat = Montserrat({
  variable:'--font-montserrat',
  subsets: ['latin']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${MontSerrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col items-center justify-center">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
